### ISSUE TITLE
CAN FD Mode and BRS Support

### ISSUE THREAD

**Issue by mesink** [CANopenNode/CanOpenSTM32#26]
Does this codebase support CAN-FD, or just standard CAN over the STM32 CANFD peripheral? I see the following:

> .\CANopenNodeSTM32 : Includes the implementation of low-level driver for STM32 microcontrollers, support both CAN based controllers and FDCAN without any changes. It automatically detect the controller type and activate the relevant calls to STM32 HAL libraries

But then this is hard coded in the driver:

https://github.com/CANopenNode/CanOpenSTM32/blob/master/CANopenNode_STM32/CO_driver_STM32.c#L267

**Comment by MaJerle** [comment]
CanOpen library does not support FDCAN to my knowledge, so not sure we can use FDCAN and BRS therefore here. Or am I wrong?

It is hardcoded, since as said above, CANopen is by default on classic CAN and we are sending classic-CAN message.

**Comment by HamedJafarzadeh** [comment]
@mesink This library support FDCAN Controllers but in the classic mode. As @MaJerle said this doesn't not support FDCAN protocol and BRS therefore.
