### ISSUE TITLE
STM32F4+FreeRTOS

### ISSUE THREAD

**Issue by rohinidr** [CANopenNode/CanOpenSTM32#29]
Hi,

I am using STM32F4 with freeRTOS. Is there a reason why the ```
CANopenNodeSTM32*
    canopenNodeSTM32 resets to junk value when it enters the `canopen_app_process`? I just see the CANopen app interrupt in between . Do I need to protect these variables using mutex?
```

**Comment by MaJerle** [comment]
Closing as unclear.
