### ISSUE TITLE
[Question] Why is the NMT state is operation after the program starts?

### ISSUE THREAD

**Issue by Ashenoneq** [CANopenNode/CanOpenSTM32#30]
Why is the NMT state  is _operation_ after the program starts? According to the state machine, should it be the _pre-operational_ state initially?

**Comment by MaJerle** [comment]
https://github.com/CANopenNode/CanOpenSTM32/blob/c7fb1def182dfee394f396739e5cc45b11f744cc/legacy/stm32h7xx_fdcan_rtos/Src/main.c#L60

**Comment by Ashenoneq** [comment]
> https://github.com/CANopenNode/CanOpenSTM32/blob/c7fb1def182dfee394f396739e5cc45b11f744cc/legacy/stm32h7xx_fdcan_rtos/Src/main.c#L60

Thinks!
