### ISSUE TITLE
How to set the STM as a NMT master and send NMT commands?

### ISSUE THREAD

**Issue by TimK456** [CANopenNode/CanOpenSTM32#32]
Hi,

I have import the CANopenNodeSTM32 to my project and configurate the heartbeat and PDOs via CANopenEditor. Thats works fine. My second device is a slave and starts in the pre-operational mode. So I would send the NMT command from the STM to set the second device to the operational mode. 

My question is now, how to set the STM to a NMT master and how can I send the NMT commands like the operational mode. I think it should be also possible to configurate it in the editor and send it.

**Comment by MaJerle** [comment]
This question is for CanOpenNode master repository. It is not STM32 specific.

**Comment by TimK456** [comment]
Okey, thank you.
