### ISSUE TITLE
Reading of Visible String Result in SDO  protocol timed out

### ISSUE THREAD

**Issue by Zeusz0** [CANopenNode/CanOpenSTM32#36]
I want to read a Visible String data type, but I always get Abbort code 0504 0000h - SDO protocol timed out.

I guess that's because I have more than 4 bytes of data, but I think that should be handled by segment/block transfer. I am having trouble finding the instructions on how to set up the block/segmented transfer options.

**Comment by MaJerle** [comment]
Please ask this to core library repository.
