### ISSUE TITLE
More just as request for help than an actual issue.

### ISSUE THREAD

**Issue by milhead2** [CANopenNode/CanOpenSTM32#50]
I've not been able to get send on COS to work on my Nucleo-STM32G474RE while most everything else is working great.  Can anyone point me to an example of setting up send on COS?

**Comment by CANopenNode** [comment]
Add extension to your OD variable. Map that variable to an event driven PDO. Monitor the variable by application and `OD_requestTPDO()` when necessary.

https://github.com/CANopenNode/CANopenDemo/blob/master/demo/CO_application.c
