### ISSUE TITLE
node ID is not added to COB ID in EDS file

### ISSUE THREAD

**Issue by Jan-Jelle** [CANopenNode/CanOpenSTM32#53]
Got the system running and regenerated a working EDS file. the only problem I encountered so far was that the Node ID was not added to the COB ID in the EDS file:

 
![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/769d71ec-c302-4887-b969-28b1db0618cc)

I have tried to add $NODEID + COBID in the EDS editor:
![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/13456b0a-c735-4905-830d-5e1ef530d2d3)

but this is not allowed.
I can do this in the Object Dictionary:
![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/fbb21f8a-77df-44f2-a681-426ab4ac8aad)
but whenever I change the PDO and save it, the value is overwritten with 0x180. 

I have now changed this in the PLC directly:
![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/11b9016d-ac91-4699-8daa-3c726ad8187c)
and this works, but is still a manual input.

is it possible to set the EDSeditor in such a way that when I create a PDO, the +$NODEID is automatically added to the EDS file?

there are default S/PDO's which do have this addition in the EDS file:
![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/f7d19b4e-f93b-44d8-ad1d-6edb362c93d8)

maybe I missed a simple setting?

**Comment by CANopenNode** [comment]
This is more question for CANopenEditor. However, in CANopeNode/example/DS301_profile.eds this seems to be correct:
https://github.com/CANopenNode/CANopenNode/blob/master/example/DS301_profile.eds#L594
Try `$NODEID+0x180`

**Comment by Jan-Jelle** [comment]
the problem only seems to exist with PDO's that are manually created. 
![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/a05b09b3-0438-48db-8e66-007c1d11d698)
0x1200 is the SDO server parameter, this indeed has the addition of $NODEID. 

the COB-ID for the RPDO in the example also has the $NODEID, like this. $NODEID+0x80000300. 
![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/b180b565-2fec-4c5a-a195-4d6dae66dace)

so only when i add $NODEID+ in the 'default' value in the Object Dictionary it does take it over correctly in the EDS file. i guess this will work, but when I change the RPDO and press 'save' i just need to remember to add this again as it overwrites with the set COB-ID from the PDO editor.

![image](https://github.com/CANopenNode/CanOpenSTM32/assets/37311655/c4d9d5a0-c893-4846-9a5c-8554d19973c4)

**Comment by CANopenNode** [comment]
CANopenEditor is quite complex GUI program, it is not so strict, as tries to be CANopenNode stack. CANopenNode exporter also ignores $NODEID keyword, default COB-IDs are handled internally "automatically". But this keyword is required for correct eds documentation file.
Please note, PDO mapping and communication parameters can be changed also dynamically on running CANopen device.

**Comment by Jan-Jelle** [comment]
adding $NODEID at the default value in EDSeditor prior to EDS export is a workable solution to this problem!
