### ISSUE TITLE
Configuring the micro as MASTER problem, CO_NMT_sendCommand() not defined.

### ISSUE THREAD

**Issue by Liuk-93** [CANopenNode/CanOpenSTM32#56]
Currently, I am working on configuring my code to enable the microcontroller as a master and send NMT command messages. I used the editor for configuration; however, I am facing difficulties as the CO_NMT_sendCommand() function is not available in the microcontroller's IDE.

Someone can explain me the rigth passage to configure the micro as Master?

Thanks

**Comment by MaJerle** [comment]
Reposting to the core repo https://github.com/CANopenNode/CANopenNode/issues/494

**Comment by andrewteta** [comment]
Placing the following near the top of CO_driver_target.h worked for me:
```
#define CO_CONFIG_NMT (CO_CONFIG_NMT_MASTER)
```

**Comment by CANopenNode** [comment]
Yes, this is the correct approach. Editor only generates Object Dictionary and some macros related to it.
