### ISSUE TITLE
Trying to receive SDO messages in SDO client over CO_SDOclient_receive

### ISSUE THREAD

**Issue by urrudelu30** [CANopenNode/CanOpenSTM32#61]
Hi, I am trying to receive messages over the RXFIFO in the SDO client, but every time a message is comming the function rejects its due to the SDO_C->state is in CO_SDO_ST_IDLE. How I can change this state, there is some function that I need to configure for starting receiving data?
Maybe I need to configure **CO_SDOclientDownloadInitiate** or **CO_SDOclientUploadInitiate**?

if (SDO_C->state != CO_SDO_ST_IDLE && DLC == 8U
        && (!CO_FLAG_READ(SDO_C->CANrxNew) || data[0] == 0x80)
    ) {

**Comment by MaJerle** [comment]
This is a question for main repository, CanOpenNode.

**Comment by urrudelu30** [comment]
Thanks ,I will ask here
