### ISSUE TITLE
Error during build project with stack STM32 

### ISSUE THREAD

**Issue by daddi1987** [CANopenNode/CanOpenSTM32#69]
Hello, 
I have a problem during compiling the my custom project with node CanOpen in STM32F769NIHx.
I added the iclude file and source file:
![image](https://github.com/user-attachments/assets/348d5344-4339-46be-80be-10a455d29e0c)
![image](https://github.com/user-attachments/assets/3aa7cdcd-1935-4796-8295-4e978108f0b7)

added #include "CO_app_STM32.h"

recall in my progect the function CanOpen
![image](https://github.com/user-attachments/assets/40e03220-5dad-4d32-962d-9a859b58ef95)

But the build not possible 
![image](https://github.com/user-attachments/assets/b303d657-e40a-41e6-93fc-402732476feb)
![image](https://github.com/user-attachments/assets/314a2332-2c2f-4031-8e6c-7863683fdea4)

This is my structure on project
![image](https://github.com/user-attachments/assets/70abf57f-7f6c-4200-b524-b022267f8ccd)

Where is the problem caused by not possible build the project?

Thank you

**Comment by MaJerle** [comment]
CanOpen files are not being picked up by the compiler, and later not by the linker.

**Comment by daddi1987** [comment]
I followed the video guide for insert the library canopen. Where is the better method for insert library?

**Comment by daddi1987** [comment]
I resolved previus problem, but i have another problem for build
No rule to make target 'CanopenNode/storage/CO_storage.o', needed by 'FDB_Basic.elf'.  Stop.
make: *** Waiting for unfinished jobs....

**Comment by daddi1987** [comment]
I managed to compile the project but I can't see the can node. I see another open bug for 500Kbit communication, like mine, but I don't see an answer to the problem

**Comment by daddi1987** [comment]
My issue wasn't resolved until I included the DS301 Object Dictionary. Most likely, the default dictionary lacks some of the necessary entries to properly turn on the LEDs and send out packets.
Thank you all
