### ISSUE TITLE
STM32 freeze in HardFault_Handler 

### ISSUE THREAD

**Issue by ruziev-dev** [CANopenNode/CanOpenSTM32#75]
I'm using CANopenNode with FreeRTOS for STM32F412RGT.

I use TIM7 for call `canopen_app_interrupt()`
Debug process shows that controller runs `HardFault_Handler` and executes it constantly.

I suppose the problem is related with interrupts settings because of if I exclude this code from `HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)`: 
```c
 if (htim == canopenNodeSTM32->timerHandle)
  {
    canopen_app_interrupt();
  }
```

or if I disable checkbox _**TIM7 global interrupt**_ MCU is not freezing.

Could anybody help with settings?

**Comment by MaJerle** [comment]
When you receive an interrupt, you can bacj trace the instruction where it happened.

canopenNodeSTM32: whats the value of this variable in debug?

**Comment by MaJerle** [comment]
Are you calling `canopen_app_interrupt();` before you initialized the canopen? You should init first.

**Comment by ruziev-dev** [comment]
@MaJerle  I don`t think so.
I have noticed, that when I set TIM7 global interrupt priority higher than otherwise i get infinite loop of `canopen_app_interrupt()`
when I change it to value 5 (equal as otherwise)  I get infinite loop of `HardFault_Handler`

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/94111d93-881c-4059-896a-eb4ef7e2ee55">

**Comment by ruziev-dev** [comment]
@MaJerle 
My problem has been fixed after disabling CO_MULTIPLE_OD flag.
I need to use multiple OD for my project for different builds and possible it has been wrong configured. 

Is there any example of STM32 project with few OD and CO_MULTIPLE_OD enabled?
