### ISSUE TITLE
0x1F80 NMTStartup  call #error

### ISSUE THREAD

**Issue by Apach200** [CANopenNode/CanOpenSTM32#79]
If in Object Dictionary Editor NMTStartup **0x1F80** enable,  then called "`#error OD_CNT_NMT from OD.h not correct!`"
In OD.h      
`#define OD_CNT_NMT 2`

**Comment by MaJerle** [comment]
Please notify the master repo. @CANopenNode

**Comment by CANopenNode** [comment]
answered https://github.com/CANopenNode/CANopenNode/issues/557
